// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CardCharacter: typeof import('./src/components/CardCharacter.vue')['default']
    CardImage: typeof import('./src/components/CardImage.vue')['default']
    ListOfCardCharacter: typeof import('./src/components/ListOfCardCharacter.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchAndFilter: typeof import('./src/components/SearchAndFilter.vue')['default']
  }
}
